name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Change directory to ./backend and Build the Docker image
      run: |
        cd ./backend
        docker build . --tag my-image-name:$(date +%s)
        IMAGE_ID=$(docker images -q my-image-name:$(date +%s))
        docker run --rm $IMAGE_ID
