name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Change directory to ./backend and Build the Docker image
      run: |
        cd ./backend
        TIMESTAMP=$(date +%s)
        IMAGE_TAG=my-image-name:$TIMESTAMP
        docker build . --tag $IMAGE_TAG
        docker run --rm $IMAGE_TAG
