name: Next.js Build and Test

on:
  push:
    branches:
      - main  # This can be adjusted to any branch you want

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout your repository code

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # Adjust Node.js version as needed

    - name: Install dependencies
      run: |
        npm install  # Install the dependencies from package.json

    - name: Run Next.js build
      run: |
        npm run build  # Build the Next.js app to make sure everything works

    - name: Run tests
      run: |
        npm run test  # Run your tests (ensure you have a test script defined in package.json)

    - name: Lint Code
      run: |
        npm run lint  # Optional: run linting if you have it configured

    - name: Check if app is working
      run: |
        npm run start &  # Start the app in the background
        sleep 10  # Wait for the app to start
        curl --fail http://localhost:3000 || exit 1  # Ensure the app is responding
